<a href="https://colab.research.google.com/github/Aakshi23/Big-Data-Analytics/blob/main/Asg2_31_jan_2024_202301001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ques-1

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1=arr[::-1]
print(arr1)

[6 5 4 3 2 1]


Ques-2

In [ ]:
import numpy as np
arr1=np.array([[4,4],[4,5]])
arr2=np.array([[1,2,3], [4,7,6]])
if(arr1.all()==arr2.all()):
  print("array is same")
else:
  print("array is not same")


array is same


Ques-3

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,4,4,4])
print("Original array:")
print(x)
print(y)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())
print("Most frequent value in the above array:")
print(np.bincount(y).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
[1 1 1 2 3 4 2 4 3 3 4 4 4]
Most frequent value in the above array:
1
Most frequent value in the above array:
4


Ques-4

In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = gfg.sum()

sum_row_wise = gfg.sum(axis=1)

sum_column_wise = gfg.sum(axis=0)

print("i. Sum of all elements:", sum_all_elements)
print("ii. Sum of all elements row-wise:", sum_row_wise)
print("iii. Sum of all elements column-wise:", sum_column_wise)

i. Sum of all elements: 45
ii. Sum of all elements row-wise: [[14]
 [16]
 [15]]
iii. Sum of all elements column-wise: [[20  9 16]]
