<a href="https://colab.research.google.com/github/Aakshi23/Big-Data-Analytics/blob/main/Labeval_mcagroup1_202301001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Multiply the following matrices and also find covariance between matrices using numpy :i
p=[[1,2],[2,3]] q=[[4,5],[6,7]]

In [13]:
import numpy as i
p = i.array([[1, 2], [2, 3]])
q = i.array([[4, 5], [6, 7]])
result = i.dot(p, q)
print("Matrix multiplication result:")
print(result)
covariance = i.cov(p,q)
print("Covariance between matrices:")
print(covariance)



Matrix multiplication result:
[[16 19]
 [26 31]]
Covariance between matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
